apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpresscd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DhiaAmmar99/Cloud-Project
    targetRevision: HEAD
    path: helm/wordpress
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress-cd 

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
